server:
  port: 8090

spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'     
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"
  
  
    
